### ISSUE TITLE
Longer module names

### ISSUE THREAD

**Issue by peso** [kevina/factoriocalc#3]
Please change the module names to real words. This would make it much easier to read and understand.
itm -> item
mch -> machine
rcp -> recipe

**Comment by kevina** [comment]
Sorry they are short by design.

**Comment by kevina** [comment]
Those modules are special and meant to always be used as part of the symbol and never on there own. They are short to be easy to type and more importantly not to conflict with symbols 'item', 'machine' and 'recipe' in local code.  The terse nature of the symbols is also meant to be a clue that they are special.
