### ISSUE TITLE
Undefined exception ValeuError

### ISSUE THREAD

**Issue by peso** [kevina/factoriocalc#4]
There is a spelling mistake "ValeuError" in blueprint.py

**Comment by peso** [comment]
Triggered by importing a blueprint with gun-turret, where position is not an integer. 

Example
`{"name":"gun-turret","position":{"x":-4.5,"y":-8.5},"direction":0,"entity_number":4}`

**Comment by kevina** [comment]
I can fix the undefined exception, but can't reproduce what is triggering it.  Can you please provide a complete blueprint sting.

**Comment by peso** [comment]
This is the blueprint string that triggers the exception for me

0eJyd1O+KgzAMAPBXkXy2w/pvm68yjqNq5hU0SluPG8N3v6rjcOjRuY9tk19CCrlDXvfYKUkGsjvIoiUN2eUOWlYk6vHO3DqEDKTBBnwg0YwnoTU2eS2pYo0oviQh4zD4IKnEH8j48OEDkpFG4uz9nxdatWu1DW1prGfTQx9ukDGeWrGUCov5LXiYt0/qmxzVWMffSZ8n2i2HCxlrG6dkwa69IlHgWmWPjp1stGCrnpjplUKzAcaHZCZPh8SFxq+i6Q40WaCSNCpjbzfIGYxcXPoad5y58JkLV9zxNe602V284k67uoufuXTFnRecUYJ01yrDcqy3PoUHs+r8ER68w6auUXK+hz1vquuJ8vANNXENlkfjYplWUbbYXD58o9JTzjEKeBKlPOHWrIWtN9ZHbbz26v1leEVbIgzDL0mCpTo=

**Comment by kevina** [comment]
The problem wasn't the gun-turret but the assembling machine.  The gun-turret should be ignored since it doesn't have a corresponding machine.

The following  code snippet reproduces the error:
```
Blueprint({'blueprint': {'entities': [{'name': 'assembling-machine-2', 'position': {'x': 2, 'y': -16}, 'direction': 0, 'entity_number': 1}]}}).convert()
```

Was that blueprint constructed by hand?  The code expects the position to be at the center of the entity.  If the width of the entity is odd (in this case 3) the position should be a fractional value.

**Comment by peso** [comment]
The final version was made with FBE
https://teoxoy.github.io/factorio-blueprint-editor/
The version inserted into FBE was a manually generated blueprint with two assembling-machine-2.
Thank you for pointing out my mistake.

**Comment by kevina** [comment]
Okay.  For now I will only support blueprints created by the game itself since I am unsure how Factorio interprets non-standard blueprints.  I will fix the typo and maybe create a better error message.
